//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LinkPro_Proyect.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DireccionMed
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DireccionMed()
        {
            this.Sucursal = new HashSet<Sucursal>();
            this.Medico = new HashSet<Medico>();
        }
    
        public int DIRECCIONMEDID { get; set; }
        public Nullable<int> ID_COMUNA { get; set; }
        public Nullable<int> ID_REGION { get; set; }
        public string DIRECCION { get; set; }
        public int ID_CIUDAD { get; set; }
    
        public virtual Ciudad Ciudad { get; set; }
        public virtual Comuna Comuna { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sucursal> Sucursal { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Medico> Medico { get; set; }
        public virtual Region Region { get; set; }
    }
}
