//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LinkPro_Proyect.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ficha
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ficha()
        {
            this.Paciente = new HashSet<Paciente>();
        }
    
        public int FICHAID { get; set; }
        public Nullable<int> ID_AFILIACION { get; set; }
        public Nullable<int> ID_SEXO { get; set; }
        public Nullable<double> MASA { get; set; }
        public Nullable<int> ALTURA { get; set; }
        public string GRUPO_SANGRE { get; set; }
        public string ENFERMEDADES { get; set; }
        public string MEDICAMENTOS { get; set; }
        public string ALERGIAS { get; set; }
        public string OBSERVACIONES { get; set; }
    
        public virtual Afiliacion Afiliacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Paciente> Paciente { get; set; }
        public virtual Sexo Sexo { get; set; }
    }
}
