//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LinkPro_Proyect.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LinkPro_Test_Old_Update : DbContext
    {
        public LinkPro_Test_Old_Update()
            : base("name=LinkPro_Test_Old_Update")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Afiliacion> Afiliacion { get; set; }
        public virtual DbSet<Citas> Citas { get; set; }
        public virtual DbSet<Ciudad> Ciudad { get; set; }
        public virtual DbSet<Comuna> Comuna { get; set; }
        public virtual DbSet<Documentos> Documentos { get; set; }
        public virtual DbSet<Especialidad> Especialidad { get; set; }
        public virtual DbSet<Estado> Estado { get; set; }
        public virtual DbSet<Ficha> Ficha { get; set; }
        public virtual DbSet<Hora> Hora { get; set; }
        public virtual DbSet<Horario> Horario { get; set; }
        public virtual DbSet<Medico> Medico { get; set; }
        public virtual DbSet<Medico_Especial> Medico_Especial { get; set; }
        public virtual DbSet<Pac_Med> Pac_Med { get; set; }
        public virtual DbSet<Paciente> Paciente { get; set; }
        public virtual DbSet<Pagina> Pagina { get; set; }
        public virtual DbSet<Region> Region { get; set; }
        public virtual DbSet<Rol> Rol { get; set; }
        public virtual DbSet<RolPagina> RolPagina { get; set; }
        public virtual DbSet<Sexo> Sexo { get; set; }
        public virtual DbSet<Sucursal> Sucursal { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
    }
}
