//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LinkPro_Proyect.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Paciente
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Paciente()
        {
            this.Citas = new HashSet<Citas>();
            this.Documentos1 = new HashSet<Documentos>();
            this.Pac_Med = new HashSet<Pac_Med>();
        }
    
        public int PACIENTEID { get; set; }
        public int ID_ROLP { get; set; }
        public int ID_USUARIO { get; set; }
        public Nullable<int> ID_FICHA { get; set; }
        public Nullable<int> ID_COMUNA { get; set; }
        public Nullable<int> ID_SEXO { get; set; }
        public Nullable<int> ID_ESTADO { get; set; }
        public Nullable<int> ID_DOCUMENTO { get; set; }
        public string NOMBRE { get; set; }
        public string APELLIDO { get; set; }
        public string RUT { get; set; }
        public string DIRECCION { get; set; }
        public string TELEFONO { get; set; }
        public Nullable<System.DateTime> FECHA_NACIMIENTO { get; set; }
        public string EMAIL { get; set; }
        public Nullable<System.DateTime> FECHA_INSCRITO { get; set; }
        public int BHABILITADO { get; set; }
        public Nullable<int> ID_CIUDAD { get; set; }
        public Nullable<int> ID_REGION { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Citas> Citas { get; set; }
        public virtual Comuna Comuna { get; set; }
        public virtual Documentos Documentos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Documentos> Documentos1 { get; set; }
        public virtual Estado Estado { get; set; }
        public virtual Ficha Ficha { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pac_Med> Pac_Med { get; set; }
        public virtual Rol Rol { get; set; }
        public virtual Sexo Sexo { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
