//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LinkPro_Proyect.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RolPagina
    {
        public int ROLPAGINAID { get; set; }
        public int ID_ROLPA { get; set; }
        public int ID_PAGINA { get; set; }
        public int BHABILITADO { get; set; }
    
        public virtual Pagina Pagina { get; set; }
        public virtual Rol Rol { get; set; }
    }
}
